### ISSUE TITLE
Unable to generate message as no changes files can be seen. Try saving your files or stage any new (untracked) files.

### ISSUE THREAD

**Issue by glassesUSA** [MichaelCurrin/auto-commit-msg#45]
![image](https://user-images.githubusercontent.com/76479522/122021593-78e28400-cdce-11eb-9784-c67cd0ff9178.png)

Says there is nothing to be updated when there are updates available

**Comment by MichaelCurrin** [comment]
Hi, thanks for message.

Please follow the instructions from the help.

>  stage any new (untracked) files

i.e. If you stage all the `U` files using VS Code UI or git CLI, then those files will be seen by the extension.

**Comment by glassesUSA** [comment]
Ahh okay thanks!

**Comment by MichaelCurrin** [comment]
Cool.

BTW for background I have notes in the docs on why handling untracked files is heavy lift in functionality and so you just have to remember to stage files yourself 

https://github.com/MichaelCurrin/auto-commit-msg/blob/master/docs/development/advanced/status-vs-diff-index.md#limitation-of-diff-index

**Comment by MichaelCurrin** [comment]
Let me know if you have any ideas on how I can reword the extensions error message that came up for you - so that it could be clearer for others who run into the same issue.

**Comment by glassesUSA** [comment]
```You have too many files to automatically commit. Please manually commit them and then repress the button```

**Comment by MichaelCurrin** [comment]
What you are suggesting could be used for the case where you commit more than X files.

I was actually referring to a message around what you had originally, not about the number of files, but that the extension saw zero files because they were all new and untracked. So I wanted to see if you had an idea to improve this:

> Try saving your files or stage any new (untracked) files.

The tip says to stage untracked files which was the solution so I don't know how to make that clearer.
